### ISSUE TITLE
Natural Mortality Spatial and Temporal upgrades

### ISSUE THREAD

**Issue by Dave-Keith** [RaphMcDo/SEBDAM#16]
1. Can we have a time varying natural mortality that isn't spatial.  Could improve our Sable model, and more generally might be of interest more broadly for stocks without a clapper index but want a random walk mortality term.
2. For the spatially variable M, can we add a prior (or something) to suggest the 'mean level' of m for a stock and let mortality varying spatially and temporally around that

**Comment by Dave-Keith** [comment]
Just tweaked my initial request asking for more :-P

**Comment by RaphMcDo** [comment]
1- This has been added to SEBDAM and SEHBAM. This required the addition of a new option in the c++ files for sebdam and sehbam, and an additional option in data_setup in temp_obs_mort that has to be =T to function. It then treats natural mortality as a temporal random walk with initial state estimated through log_m0 and a new parameter log_sigma_m.

2- This did not specifically require a new options within the model, all you need to do for spatial models is fix log_m0 to whatever you want the initial mean to be. This won't be stationary because random walks are not stationary, but as long as you don't have an insane variance within your data then it should stay broadly around that. To facilitate fixing parameters, added fix_params() function in R. To use it, need to provide the fitting object and a list with the name of the parameter you want to fix and the value you want to fix it at. For example, you would do new_obj<-fix_params(obj=tmb_obj, pars = list(log_sigma_epsilon=log(0.1)), and the result new_obj can be fed to fit_model

May 2nd 2023 commit
